name: Automated deployments to AWS' s3.

on:
  push: 
    branches: 
      - main

jobs:
  automated-building-and-deployment:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkoutv3
      - uses: actions/setup-node@v3
        with: 
          node-version: '16.20.2'

      - name: checking node version.
        run: node -v

      - name: install dependencies.
        run: npm install

      - name: building build/dist folder
        run: npm run build

        #- name: uploading to s3.
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.ACCESS_KEY }}     
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.BUCKET_NAME }}
          source_dir: build
          destination_dir: ''